### PR TITLE
WIP: Old post cleanup

### PR DESCRIPTION
**Pull request by AlanBarber**
We will merge in changes once completed.

### CODE REVIEW

**Comment by AlanBarber** [comment]
@CalvinAllen can you make a modification to the posts to include the /index.html to the end of each redirect_from: line in the posts.

**Comment by ghost** [comment]
@AlanBarber Yep - I'll add that in.

**Comment by ghost** [comment]
@AlanBarber All changes complete.  Review/merge needed.

**Comment by AlanBarber** [comment]
looks good, i'm going to do a squash and merge

**Pull request merged**
