### PR TITLE
Updated config yaml to not publish future posts

### PR DESCRIPTION
**Pull request by mgroves**
per docs: https://jekyllrb.com/docs/configuration/

### CODE REVIEW

**Comment by AlanBarber** [comment]
sorry, i just added that on the master :)

**Comment by ghost** [comment]
Added on master already; no merge.

**Comment by mgroves** [comment]
hey I'm trying to follow a process here AND YOU JUST COMPLETELY BYPASS AND ABUSE TH-

it's fine :)

**Comment by AlanBarber** [comment]
sorry, i should have done this myself, just figured i'd do a quick fix to the config :)

Alan = bad

**Pull request closed without merging**
